Algoritmo "loop5enquanto"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Sarah Maciel Braga de Aquino
// Data atual  : 01/04/2022
Var
// Seção de Declarações das variáveis 
i : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
i <- 1

enquanto i < 5 faca

  escreval (" -> i ",i , "/")
     i <- i + 1

fimenquanto

Fimalgoritmo