Algoritmo "parafaca"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Sergio
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Sarah Maciel Braga de Aquino
// Data atual  : 01/04/2022
Var
j : inteiro
// Seção de Declarações das variáveis 

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  para j de 1 ate 10 faca
  
  escreva(j:10)
  
  fimpara


Fimalgoritmo